language: cpp
sudo: true

matrix:
  include:
    #============================================================
    #
    #             Debug 
    #
    #============================================================
    #==============================
    #
    #     osx g++ 
    #
    #==============================

    #- os: osx
    #  osx_image: xcode7.3
    #  compiler: g++
    #  env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    #- os: osx
    #  osx_image: xcode8
    #  compiler: g++
    #  env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    #- os: osx
    #  osx_image: xcode9
    #  compiler: g++
    #  env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.1
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.2
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.4
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode10
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    #==============================
    #
    #     osx clang++
    #
    #==============================

    #- os: osx
    #  osx_image: xcode7.3
    #  compiler: clang++
    #  env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    #- os: osx
    #  osx_image: xcode8
    #  compiler: clang++
    #  env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    #- os: osx
    #  osx_image: xcode9
    #  compiler: clang++
    #  env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.1
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.2
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.4
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode10
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    #==============================
    #
    #     linux g++ 
    #
    #==============================
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    #==============================
    #
    #     linux clang++ 
    #
    #==============================

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    #============================================================
    #
    #             Release 
    #
    #============================================================
    #==============================
    #
    #     osx g++ 
    #
    #==============================

    #- os: osx
    #  osx_image: xcode7.3
    #  compiler: g++
    #  env: CXX=g++ CC=gcc BUILD_TYPE=Release

    #- os: osx
    #  osx_image: xcode8
    #  compiler: g++
    #  env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode8.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    #- os: osx
    #  osx_image: xcode9
    #  compiler: g++
    #  env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.1
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.2
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.4
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode10
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    #==============================
    #
    #     osx clang++
    #
    #==============================

    #- os: osx
    #  osx_image: xcode7.3
    #  compiler: clang++
    #  env: CXX=clang++ CC=clang BUILD_TYPE=Release

    #- os: osx
    #  osx_image: xcode8
    #  compiler: clang++
    #  env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    #- os: osx
    #  osx_image: xcode9
    #  compiler: clang++
    #  env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.1
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.2
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.4
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode10
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    #==============================
    #
    #     linux g++ 
    #
    #==============================
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - mpich
            - libmpich-dev
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    #==============================
    #
    #     linux clang++ 
    #
    #==============================

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - mpich
            - libmpich-dev
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

before_install:
  - eval
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      brew install openmpi;
    fi;

before_script:
  - mkdir build
  - cd build
  - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC}

script:
  - make
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      mpirun -np 5 ./openmpingine;
    fi;